### ISSUE TITLE
file not found in the dataset (raw_loop.csv). and able to conifgure this file from dataset. 

### ISSUE THREAD

**Issue by vikas-rajpoot** [risqiutama/ti-slam#9]
Traceback (most recent call last):
  File "utility/test_loop_pose_prob.py", line 129, in <module>
    main()
  File "utility/test_loop_pose_prob.py", line 54, in main
    x_image_1, x_image_2, loop_pairs_data = load_eval_data(dataroot, loop_path, eval_exp, img_h, img_w, img_c)
  File "C:\Users\BBBS\Videos\ti-slam-main\Python\odometry\utility\data_tools.py", line 60, in load_eval_data
    with open(loop_pairs_file, 'r') as pose_file:
FileNotFoundError: [Errno 2] No such file or directory: 'results//2019-11-23-15-54-25/rgb_sampled/raw_loop.csv'
Using TensorFlow backend.

where i will find the **'results//2019-11-23-15-54-25/rgb_sampled/raw_loop.csv'**  file i am not able to locate it in the dataset.

please help me out. Its very urgent.

**Comment by vikash9899** [comment]
**please help me out. Its very urgent.**
